import React from "react";

import "./map_defs.scss";

const map_day_2 = () => {
  return (
    <svg
      id="def"
      className="map_day_2"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 534.8 297.8"
    >
      <g id="A56">
        <rect
          id="A"
          className="cls-1"
          x="2"
          y="153.6"
          width="10"
          height="10"
          transform="translate(-53.8 12) rotate(-20)"
        />
        <rect
          id="A-2"
          data-name="A"
          className="cls-1"
          x="11.4"
          y="150.2"
          width="10"
          height="10"
          transform="translate(-52.1 15) rotate(-20)"
        />
        <rect
          id="A-3"
          data-name="A"
          className="cls-1"
          x="14.9"
          y="159.6"
          width="10"
          height="10"
          transform="translate(-55.1 16.7) rotate(-20)"
        />
        <rect
          id="A-4"
          data-name="A"
          className="cls-1"
          x="5.5"
          y="163"
          width="10"
          height="10"
          transform="translate(-56.8 13.7) rotate(-20)"
        />
        <rect
          id="A-5"
          data-name="A"
          className="cls-1"
          x="8.9"
          y="172.4"
          width="10"
          height="10"
          transform="translate(-59.8 15.4) rotate(-20)"
        />
        <rect
          id="A-6"
          data-name="A"
          className="cls-1"
          x="18.3"
          y="169"
          width="10"
          height="10"
          transform="translate(-58.1 18.5) rotate(-20)"
        />
        <rect
          id="A-7"
          data-name="A"
          className="cls-1"
          x="21.7"
          y="178.3"
          width="10"
          height="10"
          transform="translate(-61.1 20.2) rotate(-20)"
        />
        <rect
          id="A-8"
          data-name="A"
          className="cls-1"
          x="12.3"
          y="181.8"
          width="10"
          height="10"
          transform="translate(-62.8 17.2) rotate(-20)"
        />
      </g>
      <g id="A4">
        <rect
          id="A-9"
          data-name="A"
          className="cls-1"
          x="15.7"
          y="191.2"
          width="10"
          height="10"
          transform="translate(-65.8 18.9) rotate(-20)"
        />
        <rect
          id="A-10"
          data-name="A"
          className="cls-1"
          x="25.1"
          y="187.7"
          width="10"
          height="10"
          transform="translate(-64.1 21.9) rotate(-20)"
        />
        <rect
          id="A-11"
          data-name="A"
          className="cls-1"
          x="28.5"
          y="197.1"
          width="10"
          height="10"
          transform="translate(-67.1 23.7) rotate(-20)"
        />
        <rect
          id="A-12"
          data-name="A"
          className="cls-1"
          x="19.2"
          y="200.6"
          width="10"
          height="10"
          transform="translate(-68.8 20.7) rotate(-20)"
        />
        <rect
          id="A-13"
          data-name="A"
          className="cls-1"
          x="22.6"
          y="210"
          width="10"
          height="10"
          transform="translate(-71.9 22.4) rotate(-20)"
        />
        <rect
          id="A-14"
          data-name="A"
          className="cls-1"
          x="32"
          y="206.5"
          width="10"
          height="10"
          transform="translate(-70.1 25.4) rotate(-20)"
        />
      </g>
      <g id="A3">
        <rect
          id="A-15"
          data-name="A"
          className="cls-1"
          x="35.4"
          y="215.9"
          width="10"
          height="10"
          transform="translate(-73.1 27.1) rotate(-20)"
        />
        <rect
          id="A-16"
          data-name="A"
          className="cls-1"
          x="26"
          y="219.4"
          width="10"
          height="10"
          transform="translate(-74.9 24.1) rotate(-20)"
        />
        <rect
          id="A-17"
          data-name="A"
          className="cls-1"
          x="38.8"
          y="225.3"
          width="10"
          height="10"
          transform="translate(-76.1 28.9) rotate(-20)"
        />
        <rect
          id="A-18"
          data-name="A"
          className="cls-1"
          x="29.4"
          y="228.8"
          width="10"
          height="10"
          transform="translate(-77.9 25.9) rotate(-20)"
        />
        <rect
          id="A-19"
          data-name="A"
          className="cls-1"
          x="32.8"
          y="238.1"
          width="10"
          height="10"
          transform="translate(-80.9 27.6) rotate(-20)"
        />
        <rect
          id="A-20"
          data-name="A"
          className="cls-1"
          x="42.2"
          y="234.7"
          width="10"
          height="10"
          transform="translate(-79.1 30.6) rotate(-20)"
        />
      </g>
      <g id="A2b">
        <rect
          id="A-21"
          data-name="A"
          className="cls-1"
          x="36.3"
          y="247.5"
          width="10"
          height="10"
          transform="translate(-83.9 29.3) rotate(-20)"
        />
        <rect
          id="A-22"
          data-name="A"
          className="cls-1"
          x="45.6"
          y="244.1"
          width="10"
          height="10"
          transform="translate(-82.2 32.3) rotate(-20)"
        />
        <rect
          id="A-23"
          data-name="A"
          className="cls-1"
          x="49.1"
          y="253.5"
          width="10"
          height="10"
          transform="translate(-85.2 34.1) rotate(-20)"
        />
        <rect
          id="A-24"
          data-name="A"
          className="cls-1"
          x="39.7"
          y="256.9"
          width="10"
          height="10"
          transform="translate(-86.9 31.1) rotate(-20)"
        />
      </g>
      <g id="A0">
        <rect
          id="A-25"
          data-name="A"
          className="cls-1"
          x="43.1"
          y="266.3"
          width="10"
          height="10"
          transform="translate(-89.9 32.8) rotate(-20)"
        />
        <rect
          id="A-26"
          data-name="A"
          className="cls-1"
          x="52.5"
          y="262.9"
          width="10"
          height="10"
          transform="translate(-88.2 35.8) rotate(-20)"
        />
        <rect
          id="A-27"
          data-name="A"
          className="cls-1"
          x="55.9"
          y="272.3"
          width="10"
          height="10"
          transform="translate(-91.2 37.6) rotate(-20)"
        />
        <rect
          id="A-28"
          data-name="A"
          className="cls-1"
          x="46.5"
          y="275.7"
          width="10"
          height="10"
          transform="translate(-92.9 34.5) rotate(-20)"
        />
        <rect
          id="A-29"
          data-name="A"
          className="cls-1"
          x="59.3"
          y="281.7"
          width="10"
          height="10"
          transform="translate(-94.2 39.3) rotate(-20)"
        />
        <rect
          id="A-30"
          data-name="A"
          className="cls-1"
          x="49.9"
          y="285.1"
          width="10"
          height="10"
          transform="translate(-95.9 36.3) rotate(-20)"
        />
      </g>
      <g id="A12">
        <rect
          id="A-31"
          data-name="A"
          className="cls-1"
          x="149.2"
          y="3"
          width="10"
          height="10"
          transform="translate(16.6 78.2) rotate(-30)"
        />
        <rect
          id="A-32"
          data-name="A"
          className="cls-1"
          x="154.2"
          y="11.7"
          width="10"
          height="10"
          transform="translate(13 81.8) rotate(-30)"
        />
        <rect
          id="A-33"
          data-name="A"
          className="cls-1"
          x="145.5"
          y="16.7"
          width="10"
          height="10"
          transform="translate(9.3 78.2) rotate(-30)"
        />
        <rect
          id="A-34"
          data-name="A"
          className="cls-1"
          x="140.5"
          y="8"
          width="10"
          height="10"
          transform="translate(13 74.5) rotate(-30)"
        />
      </g>
      <g id="A11">
        <rect
          id="A-35"
          data-name="A"
          className="cls-1"
          x="131.9"
          y="13"
          width="10"
          height="10"
          transform="translate(9.3 70.8) rotate(-30)"
        />
        <rect
          id="A-36"
          data-name="A"
          className="cls-1"
          x="136.9"
          y="21.7"
          width="10"
          height="10"
          transform="translate(5.7 74.5) rotate(-30)"
        />
        <rect
          id="A-37"
          data-name="A"
          className="cls-1"
          x="128.2"
          y="26.7"
          width="10"
          height="10"
          transform="translate(2 70.8) rotate(-30)"
        />
        <rect
          id="A-38"
          data-name="A"
          className="cls-1"
          x="123.2"
          y="18"
          width="10"
          height="10"
          transform="translate(5.7 67.2) rotate(-30)"
        />
        <rect
          id="A-39"
          data-name="A"
          className="cls-1"
          x="119.5"
          y="31.7"
          width="10"
          height="10"
          transform="translate(-1.7 67.2) rotate(-30)"
        />
        <rect
          id="A-40"
          data-name="A"
          className="cls-1"
          x="114.5"
          y="23"
          width="10"
          height="10"
          transform="translate(2 63.5) rotate(-30)"
        />
      </g>
      <g id="A10b">
        <rect
          id="A-41"
          data-name="A"
          className="cls-1"
          x="110.9"
          y="36.7"
          width="10"
          height="10"
          transform="translate(-5.3 63.5) rotate(-30)"
        />
        <rect
          id="A-42"
          data-name="A"
          className="cls-1"
          x="105.9"
          y="28"
          width="10"
          height="10"
          transform="translate(-1.7 59.9) rotate(-30)"
        />
        <rect
          id="A-43"
          data-name="A"
          className="cls-1"
          x="97.2"
          y="33"
          width="10"
          height="10"
          transform="translate(-5.3 56.2) rotate(-30)"
        />
        <rect
          id="A-44"
          data-name="A"
          className="cls-1"
          x="102.2"
          y="41.7"
          width="10"
          height="10"
          transform="translate(-9 59.9) rotate(-30)"
        />
      </g>
      <g id="A10a">
        <rect
          id="A-45"
          data-name="A"
          className="cls-1"
          x="93.6"
          y="46.7"
          width="10"
          height="10"
          transform="translate(-12.6 56.2) rotate(-30)"
        />
        <rect
          id="A-46"
          data-name="A"
          className="cls-1"
          x="88.6"
          y="38"
          width="10"
          height="10"
          transform="translate(-9 52.5) rotate(-30)"
        />
        <rect
          id="A-47"
          data-name="A"
          className="cls-1"
          x="84.9"
          y="51.7"
          width="10"
          height="10"
          transform="translate(-16.3 52.5) rotate(-30)"
        />
        <rect
          id="A-48"
          data-name="A"
          className="cls-1"
          x="79.9"
          y="43"
          width="10"
          height="10"
          transform="translate(-12.6 48.9) rotate(-30)"
        />
      </g>
      <g id="A9">
        <rect
          id="A-49"
          data-name="A"
          className="cls-1"
          x="71.2"
          y="48"
          width="10"
          height="10"
          transform="translate(-16.3 45.2) rotate(-30)"
        />
        <rect
          id="A-50"
          data-name="A"
          className="cls-1"
          x="76.2"
          y="56.7"
          width="10"
          height="10"
          transform="translate(-20 48.9) rotate(-30)"
        />
        <rect
          id="A-51"
          data-name="A"
          className="cls-1"
          x="62.6"
          y="53"
          width="10"
          height="10"
          transform="translate(-20 41.6) rotate(-30)"
        />
        <rect
          id="A-52"
          data-name="A"
          className="cls-1"
          x="67.6"
          y="61.7"
          width="10"
          height="10"
          transform="translate(-23.6 45.2) rotate(-30)"
        />
      </g>
      <g id="A78">
        <rect
          id="A-53"
          data-name="A"
          className="cls-1"
          x="58.9"
          y="66.7"
          width="10"
          height="10"
          transform="translate(-27.3 41.6) rotate(-30)"
        />
        <rect
          id="A-54"
          data-name="A"
          className="cls-1"
          x="53.9"
          y="58"
          width="10"
          height="10"
          transform="translate(-23.6 37.9) rotate(-30)"
        />
        <rect
          id="A-55"
          data-name="A"
          className="cls-1"
          x="45.3"
          y="63"
          width="10"
          height="10"
          transform="translate(-27.3 34.2) rotate(-30)"
        />
        <rect
          id="A-56"
          data-name="A"
          className="cls-1"
          x="50.3"
          y="71.7"
          width="10"
          height="10"
          transform="translate(-30.9 37.9) rotate(-30)"
        />
        <rect
          id="A-57"
          data-name="A"
          className="cls-1"
          x="41.6"
          y="76.7"
          width="10"
          height="10"
          transform="translate(-34.6 34.2) rotate(-30)"
        />
        <rect
          id="A-58"
          data-name="A"
          className="cls-1"
          x="36.6"
          y="68"
          width="10"
          height="10"
          transform="translate(-30.9 30.6) rotate(-30)"
        />
        <rect
          id="A-59"
          data-name="A"
          className="cls-1"
          x="32.9"
          y="81.7"
          width="10"
          height="10"
          transform="translate(-38.3 30.6) rotate(-30)"
        />
        <rect
          id="A-60"
          data-name="A"
          className="cls-1"
          x="27.9"
          y="73"
          width="10"
          height="10"
          transform="translate(-34.6 26.9) rotate(-30)"
        />
      </g>
      <g id="A7a">
        <rect
          id="A-61"
          data-name="A"
          className="cls-1"
          x="19.3"
          y="78"
          width="10"
          height="10"
          transform="translate(-38.3 23.3) rotate(-30)"
        />
        <rect
          id="A-62"
          data-name="A"
          className="cls-1"
          x="24.3"
          y="86.7"
          width="10"
          height="10"
          transform="translate(-41.9 26.9) rotate(-30)"
        />
        <rect
          id="A-63"
          data-name="A"
          className="cls-1"
          x="10.6"
          y="83"
          width="10"
          height="10"
          transform="translate(-41.9 19.6) rotate(-30)"
        />
        <rect
          id="A-64"
          data-name="A"
          className="cls-1"
          x="15.6"
          y="91.7"
          width="10"
          height="10"
          transform="translate(-45.6 23.3) rotate(-30)"
        />
      </g>
      <g id="B8b">
        <rect
          id="B"
          className="cls-1"
          x="167.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="B-2"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="B-3"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="B-4"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="137.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B8a">
        <rect
          id="B-5"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-6"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-7"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="B-8"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B9">
        <rect
          id="B-9"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="B-10"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="B-11"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="B-12"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="B-13"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-14"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-15"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="B-16"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B7">
        <rect
          id="B-17"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-18"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-19"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-20"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-21"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="B-22"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B10">
        <rect
          id="B-23"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-24"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-25"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-26"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-27"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="B-28"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B6">
        <rect
          id="B-29"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-30"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-31"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-32"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-33"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="B-34"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="B-35"
          data-name="B"
          className="cls-1"
          x="177.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="B-36"
          data-name="B"
          className="cls-1"
          x="167.4"
          y="227.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B11">
        <rect
          id="B-37"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-38"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-39"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-40"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-41"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="B-42"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="B-43"
          data-name="B"
          className="cls-1"
          x="197.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="B-44"
          data-name="B"
          className="cls-1"
          x="187.4"
          y="227.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B4">
        <rect
          id="B-45"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-46"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="B-47"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-48"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="B-49"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="B-50"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B5">
        <rect
          id="B-51"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-52"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="B-53"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-54"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="B-55"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="B-56"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="217.3"
          width="10"
          height="10"
        />
      </g>
      <g id="B1">
        <rect
          id="B-57"
          data-name="B"
          className="cls-1"
          x="86.2"
          y="190.9"
          width="10"
          height="10"
          transform="translate(-59 40.6) rotate(-19.1)"
        />
        <rect
          id="B-58"
          data-name="B"
          className="cls-1"
          x="76.8"
          y="194.2"
          width="10"
          height="10"
          transform="translate(-60.6 37.7) rotate(-19.1)"
        />
        <rect
          id="B-59"
          data-name="B"
          className="cls-1"
          x="80.1"
          y="203.6"
          width="10"
          height="10"
          transform="translate(-63.5 39.2) rotate(-19.1)"
        />
        <rect
          id="B-60"
          data-name="B"
          className="cls-1"
          x="89.5"
          y="200.3"
          width="10"
          height="10"
          transform="translate(-61.9 42.2) rotate(-19.1)"
        />
        <rect
          id="B-61"
          data-name="B"
          className="cls-1"
          x="92.8"
          y="209.8"
          width="10"
          height="10"
          transform="translate(-64.8 43.7) rotate(-19.1)"
        />
        <rect
          id="B-62"
          data-name="B"
          className="cls-1"
          x="83.3"
          y="213.1"
          width="10"
          height="10"
          transform="translate(-66.4 40.8) rotate(-19.1)"
        />
        <rect
          id="B-63"
          data-name="B"
          className="cls-1"
          x="86.6"
          y="222.5"
          width="10"
          height="10"
          transform="translate(-69.3 42.4) rotate(-19.1)"
        />
        <rect
          id="B-64"
          data-name="B"
          className="cls-1"
          x="96"
          y="219.3"
          width="10"
          height="10"
          transform="translate(-67.7 45.3) rotate(-19.1)"
        />
      </g>
      <g id="B2">
        <rect
          id="B-65"
          data-name="B"
          className="cls-1"
          x="73.2"
          y="153.1"
          width="10"
          height="10"
          transform="translate(-47.4 34.2) rotate(-19.1)"
        />
        <rect
          id="B-66"
          data-name="B"
          className="cls-1"
          x="63.7"
          y="156.4"
          width="10"
          height="10"
          transform="translate(-49 31.3) rotate(-19.1)"
        />
        <rect
          id="B-67"
          data-name="B"
          className="cls-1"
          x="67"
          y="165.8"
          width="10"
          height="10"
          transform="translate(-51.9 32.9) rotate(-19.1)"
        />
        <rect
          id="B-68"
          data-name="B"
          className="cls-1"
          x="76.4"
          y="162.5"
          width="10"
          height="10"
          transform="translate(-50.3 35.8) rotate(-19.1)"
        />
        <rect
          id="B-69"
          data-name="B"
          className="cls-1"
          x="79.7"
          y="172"
          width="10"
          height="10"
          transform="translate(-53.2 37.4) rotate(-19.1)"
        />
        <rect
          id="B-70"
          data-name="B"
          className="cls-1"
          x="70.2"
          y="175.3"
          width="10"
          height="10"
          transform="translate(-54.8 34.5) rotate(-19.1)"
        />
        <rect
          id="B-71"
          data-name="B"
          className="cls-1"
          x="73.5"
          y="184.7"
          width="10"
          height="10"
          transform="translate(-57.7 36.1) rotate(-19.1)"
        />
        <rect
          id="B-72"
          data-name="B"
          className="cls-1"
          x="83"
          y="181.4"
          width="10"
          height="10"
          transform="translate(-56.1 39) rotate(-19.1)"
        />
      </g>
      <g id="B3">
        <rect
          id="B-73"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-74"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-75"
          data-name="B"
          className="cls-1"
          x="117.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="B-76"
          data-name="B"
          className="cls-1"
          x="107.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="B-77"
          data-name="B"
          className="cls-1"
          x="87.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-78"
          data-name="B"
          className="cls-1"
          x="97.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="B-79"
          data-name="B"
          className="cls-1"
          x="97.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="B-80"
          data-name="B"
          className="cls-1"
          x="87.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C6">
        <rect
          id="C"
          className="cls-1"
          x="247.4"
          y="97.3"
          width="10"
          height="10"
        />
        <rect
          id="C-2"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="97.3"
          width="10"
          height="10"
        />
        <rect
          id="C-3"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="97.3"
          width="10"
          height="10"
        />
        <rect
          id="C-4"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="97.3"
          width="10"
          height="10"
        />
        <rect
          id="C-5"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="107.3"
          width="10"
          height="10"
        />
        <rect
          id="C-6"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="107.3"
          width="10"
          height="10"
        />
        <rect
          id="C-7"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="107.3"
          width="10"
          height="10"
        />
        <rect
          id="C-8"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="107.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C5">
        <rect
          id="C-9"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="117.3"
          width="10"
          height="10"
        />
        <rect
          id="C-10"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="117.3"
          width="10"
          height="10"
        />
        <rect
          id="C-11"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="C-12"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="C-13"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="C-14"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="137.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C7">
        <rect
          id="C-15"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="117.3"
          width="10"
          height="10"
        />
        <rect
          id="C-16"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="117.3"
          width="10"
          height="10"
        />
        <rect
          id="C-17"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="C-18"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="C-19"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="C-20"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="137.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C8a">
        <rect
          id="C-21"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="C-22"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="C-23"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="C-24"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="A2a">
        <rect
          id="C-25"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="C-26"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="C-27"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="C-28"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C8b">
        <rect
          id="C-29"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="C-30"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="C-31"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="C-32"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="177.3"
          width="10"
          height="10"
        />
      </g>
      <g id="A1">
        <rect
          id="C-33"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="C-34"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="C-35"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="C-36"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="177.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C2">
        <rect
          id="C-37"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="C-38"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="C-39"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="C-40"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="C-41"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="C-42"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="C-43"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="C-44"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="217.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C4">
        <rect
          id="C-45"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="C-46"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="C-47"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="C-48"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="C-49"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="C-50"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="C-51"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="C-52"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="217.3"
          width="10"
          height="10"
        />
      </g>
      <g id="C1">
        <rect
          id="C-53"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="C-54"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="C-55"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="C-56"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="C-57"
          data-name="C"
          className="cls-1"
          x="247.4"
          y="237.3"
          width="10"
          height="10"
        />
        <rect
          id="C-58"
          data-name="C"
          className="cls-1"
          x="257.4"
          y="237.3"
          width="10"
          height="10"
        />
        <rect
          id="C-59"
          data-name="C"
          className="cls-1"
          x="267.4"
          y="237.3"
          width="10"
          height="10"
        />
        <rect
          id="C-60"
          data-name="C"
          className="cls-1"
          x="277.4"
          y="237.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D4b">
        <rect
          id="D"
          className="cls-1"
          x="347.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="D-2"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="D-3"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="D-4"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="137.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D3">
        <rect
          id="D-5"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="D-6"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="127.3"
          width="10"
          height="10"
        />
        <rect
          id="D-7"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="D-8"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="137.3"
          width="10"
          height="10"
        />
        <rect
          id="D-9"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-10"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-11"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="D-12"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D4a">
        <rect
          id="D-13"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-14"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-15"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="D-16"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D2">
        <rect
          id="D-17"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-18"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-19"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-20"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-21"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="D-22"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D5">
        <rect
          id="D-23"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-24"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-25"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-26"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-27"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="D-28"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D1">
        <rect
          id="D-29"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-30"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-31"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-32"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-33"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="D-34"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="D-35"
          data-name="D"
          className="cls-1"
          x="337.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="D-36"
          data-name="D"
          className="cls-1"
          x="327.4"
          y="227.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D6">
        <rect
          id="D-37"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-38"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-39"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-40"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-41"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="D-42"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="D-43"
          data-name="D"
          className="cls-1"
          x="347.4"
          y="227.3"
          width="10"
          height="10"
        />
        <rect
          id="D-44"
          data-name="D"
          className="cls-1"
          x="357.4"
          y="227.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D9">
        <rect
          id="D-45"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-46"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-47"
          data-name="D"
          className="cls-1"
          x="427.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-48"
          data-name="D"
          className="cls-1"
          x="437.4"
          y="147.3"
          width="10"
          height="10"
        />
        <rect
          id="D-49"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="D-50"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="D-51"
          data-name="D"
          className="cls-1"
          x="427.4"
          y="157.3"
          width="10"
          height="10"
        />
        <rect
          id="D-52"
          data-name="D"
          className="cls-1"
          x="437.4"
          y="157.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D8">
        <rect
          id="D-53"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-54"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="167.3"
          width="10"
          height="10"
        />
        <rect
          id="D-55"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-56"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="177.3"
          width="10"
          height="10"
        />
        <rect
          id="D-57"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="187.3"
          width="10"
          height="10"
        />
        <rect
          id="D-58"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="187.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D7">
        <rect
          id="D-59"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-60"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="197.3"
          width="10"
          height="10"
        />
        <rect
          id="D-61"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-62"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="207.3"
          width="10"
          height="10"
        />
        <rect
          id="D-63"
          data-name="D"
          className="cls-1"
          x="407.4"
          y="217.3"
          width="10"
          height="10"
        />
        <rect
          id="D-64"
          data-name="D"
          className="cls-1"
          x="417.4"
          y="217.3"
          width="10"
          height="10"
        />
      </g>
      <g id="D10">
        <rect
          id="D-65"
          data-name="D"
          className="cls-1"
          x="451.7"
          y="153.1"
          width="10"
          height="10"
          transform="translate(157.8 537.9) rotate(-70.9)"
        />
        <rect
          id="D-66"
          data-name="D"
          className="cls-1"
          x="461.1"
          y="156.4"
          width="10"
          height="10"
          transform="translate(161.1 549) rotate(-70.9)"
        />
        <rect
          id="D-67"
          data-name="D"
          className="cls-1"
          x="448.4"
          y="162.6"
          width="10"
          height="10"
          transform="translate(146.7 541.2) rotate(-70.9)"
        />
        <rect
          id="D-68"
          data-name="D"
          className="cls-1"
          x="457.8"
          y="165.8"
          width="10"
          height="10"
          transform="translate(150 552.3) rotate(-70.9)"
        />
      </g>
      <g id="D11">
        <rect
          id="D-69"
          data-name="D"
          className="cls-1"
          x="445.1"
          y="172"
          width="10"
          height="10"
          transform="translate(135.6 544.4) rotate(-70.9)"
        />
        <rect
          id="D-70"
          data-name="D"
          className="cls-1"
          x="454.6"
          y="175.3"
          width="10"
          height="10"
          transform="translate(138.8 555.6) rotate(-70.9)"
        />
        <rect
          id="D-71"
          data-name="D"
          className="cls-1"
          x="441.9"
          y="181.5"
          width="10"
          height="10"
          transform="translate(124.4 547.7) rotate(-70.9)"
        />
        <rect
          id="D-72"
          data-name="D"
          className="cls-1"
          x="451.3"
          y="184.7"
          width="10"
          height="10"
          transform="translate(127.7 558.8) rotate(-70.9)"
        />
      </g>
      <g id="D12">
        <rect
          id="D-73"
          data-name="D"
          className="cls-1"
          x="438.6"
          y="190.9"
          width="10"
          height="10"
          transform="translate(113.3 551) rotate(-70.9)"
        />
        <rect
          id="D-74"
          data-name="D"
          className="cls-1"
          x="448"
          y="194.2"
          width="10"
          height="10"
          transform="translate(116.6 562.1) rotate(-70.9)"
        />
        <rect
          id="D-75"
          data-name="D"
          className="cls-1"
          x="435.3"
          y="200.4"
          width="10"
          height="10"
          transform="translate(102.2 554.2) rotate(-70.9)"
        />
        <rect
          id="D-76"
          data-name="D"
          className="cls-1"
          x="444.8"
          y="203.6"
          width="10"
          height="10"
          transform="translate(105.4 565.3) rotate(-70.9)"
        />
        <rect
          id="D-77"
          data-name="D"
          className="cls-1"
          x="432"
          y="209.8"
          width="10"
          height="10"
          transform="translate(91 557.5) rotate(-70.9)"
        />
        <rect
          id="D-78"
          data-name="D"
          className="cls-1"
          x="441.5"
          y="213.1"
          width="10"
          height="10"
          transform="translate(94.3 568.6) rotate(-70.9)"
        />
        <rect
          id="D-79"
          data-name="D"
          className="cls-1"
          x="438.2"
          y="222.5"
          width="10"
          height="10"
          transform="translate(83.2 571.9) rotate(-70.9)"
        />
        <rect
          id="D-80"
          data-name="D"
          className="cls-1"
          x="428.8"
          y="219.3"
          width="10"
          height="10"
          transform="translate(79.9 560.7) rotate(-70.9)"
        />
      </g>
      <g id="E12">
        <rect
          id="E"
          className="cls-1"
          x="370.6"
          y="11.2"
          width="10"
          height="10"
          transform="translate(173.8 333.4) rotate(-60)"
        />
        <rect
          id="E-2"
          data-name="E"
          className="cls-1"
          x="375.6"
          y="2.5"
          width="10"
          height="10"
          transform="translate(183.8 333.4) rotate(-60)"
        />
        <rect
          id="E-3"
          data-name="E"
          className="cls-1"
          x="379.3"
          y="16.2"
          width="10"
          height="10"
          transform="translate(173.8 343.4) rotate(-60)"
        />
        <rect
          id="E-4"
          data-name="E"
          className="cls-1"
          x="384.3"
          y="7.5"
          width="10"
          height="10"
          transform="translate(183.8 343.4) rotate(-60)"
        />
      </g>
      <g id="E11">
        <rect
          id="E-5"
          data-name="E"
          className="cls-1"
          x="387.9"
          y="21.2"
          width="10"
          height="10"
          transform="translate(173.8 353.4) rotate(-60)"
        />
        <rect
          id="E-6"
          data-name="E"
          className="cls-1"
          x="392.9"
          y="12.5"
          width="10"
          height="10"
          transform="translate(183.8 353.4) rotate(-60)"
        />
        <rect
          id="E-7"
          data-name="E"
          className="cls-1"
          x="396.6"
          y="26.2"
          width="10"
          height="10"
          transform="translate(173.8 363.4) rotate(-60)"
        />
        <rect
          id="E-8"
          data-name="E"
          className="cls-1"
          x="401.6"
          y="17.5"
          width="10"
          height="10"
          transform="translate(183.8 363.4) rotate(-60)"
        />
      </g>
      <g id="E10">
        <rect
          id="E-9"
          data-name="E"
          className="cls-1"
          x="405.3"
          y="31.2"
          width="10"
          height="10"
          transform="translate(173.8 373.4) rotate(-60)"
        />
        <rect
          id="E-10"
          data-name="E"
          className="cls-1"
          x="410.3"
          y="22.5"
          width="10"
          height="10"
          transform="translate(183.8 373.4) rotate(-60)"
        />
        <rect
          id="E-11"
          data-name="E"
          className="cls-1"
          x="413.9"
          y="36.2"
          width="10"
          height="10"
          transform="translate(173.8 383.4) rotate(-60)"
        />
        <rect
          id="E-12"
          data-name="E"
          className="cls-1"
          x="418.9"
          y="27.5"
          width="10"
          height="10"
          transform="translate(183.8 383.4) rotate(-60)"
        />
      </g>
      <g id="E9b">
        <rect
          id="E-13"
          data-name="E"
          className="cls-1"
          x="422.6"
          y="41.2"
          width="10"
          height="10"
          transform="translate(173.8 393.4) rotate(-60)"
        />
        <rect
          id="E-14"
          data-name="E"
          className="cls-1"
          x="427.6"
          y="32.5"
          width="10"
          height="10"
          transform="translate(183.8 393.4) rotate(-60)"
        />
        <rect
          id="E-15"
          data-name="E"
          className="cls-1"
          x="431.2"
          y="46.2"
          width="10"
          height="10"
          transform="translate(173.8 403.4) rotate(-60)"
        />
        <rect
          id="E-16"
          data-name="E"
          className="cls-1"
          x="436.2"
          y="37.5"
          width="10"
          height="10"
          transform="translate(183.8 403.4) rotate(-60)"
        />
      </g>
      <g id="E9a">
        <rect
          id="E-17"
          data-name="E"
          className="cls-1"
          x="439.9"
          y="51.2"
          width="10"
          height="10"
          transform="translate(173.8 413.4) rotate(-60)"
        />
        <rect
          id="E-18"
          data-name="E"
          className="cls-1"
          x="444.9"
          y="42.5"
          width="10"
          height="10"
          transform="translate(183.8 413.4) rotate(-60)"
        />
        <rect
          id="E-19"
          data-name="E"
          className="cls-1"
          x="448.6"
          y="56.2"
          width="10"
          height="10"
          transform="translate(173.8 423.4) rotate(-60)"
        />
        <rect
          id="E-20"
          data-name="E"
          className="cls-1"
          x="453.6"
          y="47.5"
          width="10"
          height="10"
          transform="translate(183.8 423.4) rotate(-60)"
        />
      </g>
      <g id="E8">
        <rect
          id="E-21"
          data-name="E"
          className="cls-1"
          x="457.2"
          y="61.2"
          width="10"
          height="10"
          transform="translate(173.8 433.4) rotate(-60)"
        />
        <rect
          id="E-22"
          data-name="E"
          className="cls-1"
          x="462.2"
          y="52.5"
          width="10"
          height="10"
          transform="translate(183.8 433.4) rotate(-60)"
        />
        <rect
          id="E-23"
          data-name="E"
          className="cls-1"
          x="465.9"
          y="66.2"
          width="10"
          height="10"
          transform="translate(173.8 443.4) rotate(-60)"
        />
        <rect
          id="E-24"
          data-name="E"
          className="cls-1"
          x="470.9"
          y="57.5"
          width="10"
          height="10"
          transform="translate(183.8 443.4) rotate(-60)"
        />
      </g>
      <g id="E7">
        <rect
          id="E-25"
          data-name="E"
          className="cls-1"
          x="474.5"
          y="71.2"
          width="10"
          height="10"
          transform="translate(173.8 453.4) rotate(-60)"
        />
        <rect
          id="E-26"
          data-name="E"
          className="cls-1"
          x="479.5"
          y="62.5"
          width="10"
          height="10"
          transform="translate(183.8 453.4) rotate(-60)"
        />
        <rect
          id="E-27"
          data-name="E"
          className="cls-1"
          x="483.2"
          y="76.2"
          width="10"
          height="10"
          transform="translate(173.8 463.4) rotate(-60)"
        />
        <rect
          id="E-28"
          data-name="E"
          className="cls-1"
          x="488.2"
          y="67.5"
          width="10"
          height="10"
          transform="translate(183.8 463.4) rotate(-60)"
        />
      </g>
      <g id="E6">
        <rect
          id="E-29"
          data-name="E"
          className="cls-1"
          x="496.9"
          y="72.5"
          width="10"
          height="10"
          transform="translate(183.8 473.4) rotate(-60)"
        />
        <rect
          id="E-30"
          data-name="E"
          className="cls-1"
          x="500.5"
          y="86.2"
          width="10"
          height="10"
          transform="translate(173.8 483.4) rotate(-60)"
        />
        <rect
          id="E-31"
          data-name="E"
          className="cls-1"
          x="505.5"
          y="77.5"
          width="10"
          height="10"
          transform="translate(183.8 483.4) rotate(-60)"
        />
        <rect
          id="E-32"
          data-name="E"
          className="cls-1"
          x="509.2"
          y="91.2"
          width="10"
          height="10"
          transform="translate(173.8 493.4) rotate(-60)"
        />
        <rect
          id="E-33"
          data-name="E"
          className="cls-1"
          x="514.2"
          y="82.5"
          width="10"
          height="10"
          transform="translate(183.8 493.4) rotate(-60)"
        />
        <rect
          id="E-34"
          data-name="E"
          className="cls-1"
          x="491.9"
          y="81.2"
          width="10"
          height="10"
          transform="translate(173.8 473.4) rotate(-60)"
        />
      </g>
      <g id="E5b">
        <rect
          id="E-35"
          data-name="E"
          className="cls-1"
          x="513.4"
          y="150.2"
          width="10"
          height="10"
          transform="translate(195.3 589.2) rotate(-70)"
        />
        <rect
          id="E-36"
          data-name="E"
          className="cls-1"
          x="522.7"
          y="153.6"
          width="10"
          height="10"
          transform="translate(198.2 600.3) rotate(-70)"
        />
        <rect
          id="E-37"
          data-name="E"
          className="cls-1"
          x="509.9"
          y="159.6"
          width="10"
          height="10"
          transform="translate(184.2 592.2) rotate(-70)"
        />
        <rect
          id="E-38"
          data-name="E"
          className="cls-1"
          x="519.3"
          y="163"
          width="10"
          height="10"
          transform="translate(187.2 603.2) rotate(-70)"
        />
      </g>
      <g id="E5a">
        <rect
          id="E-39"
          data-name="E"
          className="cls-1"
          x="506.5"
          y="169"
          width="10"
          height="10"
          transform="translate(173.1 595.1) rotate(-70)"
        />
        <rect
          id="E-40"
          data-name="E"
          className="cls-1"
          x="515.9"
          y="172.4"
          width="10"
          height="10"
          transform="translate(176.1 606.2) rotate(-70)"
        />
        <rect
          id="E-41"
          data-name="E"
          className="cls-1"
          x="503.1"
          y="178.3"
          width="10"
          height="10"
          transform="translate(162 598.1) rotate(-70)"
        />
        <rect
          id="E-42"
          data-name="E"
          className="cls-1"
          x="512.5"
          y="181.8"
          width="10"
          height="10"
          transform="translate(165 609.2) rotate(-70)"
        />
      </g>
      <g id="E4">
        <rect
          id="E-43"
          data-name="E"
          className="cls-1"
          x="499.7"
          y="187.7"
          width="10"
          height="10"
          transform="translate(150.9 601.1) rotate(-70)"
        />
        <rect
          id="E-44"
          data-name="E"
          className="cls-1"
          x="509.1"
          y="191.2"
          width="10"
          height="10"
          transform="translate(153.9 612.1) rotate(-70)"
        />
        <rect
          id="E-45"
          data-name="E"
          className="cls-1"
          x="496.3"
          y="197.1"
          width="10"
          height="10"
          transform="translate(139.9 604) rotate(-70)"
        />
        <rect
          id="E-46"
          data-name="E"
          className="cls-1"
          x="505.6"
          y="200.6"
          width="10"
          height="10"
          transform="translate(142.8 615.1) rotate(-70)"
        />
        <rect
          id="E-47"
          data-name="E"
          className="cls-1"
          x="492.8"
          y="206.5"
          width="10"
          height="10"
          transform="translate(128.8 607) rotate(-70)"
        />
        <rect
          id="E-48"
          data-name="E"
          className="cls-1"
          x="502.2"
          y="210"
          width="10"
          height="10"
          transform="translate(131.8 618.1) rotate(-70)"
        />
      </g>
      <g id="E3">
        <rect
          id="E-49"
          data-name="E"
          className="cls-1"
          x="489.4"
          y="215.9"
          width="10"
          height="10"
          transform="translate(117.7 610) rotate(-70)"
        />
        <rect
          id="E-50"
          data-name="E"
          className="cls-1"
          x="498.8"
          y="219.4"
          width="10"
          height="10"
          transform="translate(120.7 621) rotate(-70)"
        />
        <rect
          id="E-51"
          data-name="E"
          className="cls-1"
          x="486"
          y="225.3"
          width="10"
          height="10"
          transform="translate(106.6 612.9) rotate(-70)"
        />
        <rect
          id="E-52"
          data-name="E"
          className="cls-1"
          x="495.4"
          y="228.8"
          width="10"
          height="10"
          transform="translate(109.6 624) rotate(-70)"
        />
        <rect
          id="E-53"
          data-name="E"
          className="cls-1"
          x="482.6"
          y="234.7"
          width="10"
          height="10"
          transform="translate(95.5 615.9) rotate(-70)"
        />
        <rect
          id="E-54"
          data-name="E"
          className="cls-1"
          x="492"
          y="238.1"
          width="10"
          height="10"
          transform="translate(98.5 627) rotate(-70)"
        />
      </g>
      <g id="E2">
        <rect
          id="E-55"
          data-name="E"
          className="cls-1"
          x="479.2"
          y="244.1"
          width="10"
          height="10"
          transform="translate(84.5 618.9) rotate(-70)"
        />
        <rect
          id="E-56"
          data-name="E"
          className="cls-1"
          x="488.5"
          y="247.5"
          width="10"
          height="10"
          transform="translate(87.4 630) rotate(-70)"
        />
        <rect
          id="E-57"
          data-name="E"
          className="cls-1"
          x="475.7"
          y="253.5"
          width="10"
          height="10"
          transform="translate(73.4 621.8) rotate(-70)"
        />
        <rect
          id="E-58"
          data-name="E"
          className="cls-1"
          x="485.1"
          y="256.9"
          width="10"
          height="10"
          transform="translate(76.3 632.9) rotate(-70)"
        />
      </g>
      <g id="E1">
        <rect
          id="E-59"
          data-name="E"
          className="cls-1"
          x="472.3"
          y="262.9"
          width="10"
          height="10"
          transform="translate(62.3 624.8) rotate(-70)"
        />
        <rect
          id="E-60"
          data-name="E"
          className="cls-1"
          x="481.7"
          y="266.3"
          width="10"
          height="10"
          transform="translate(65.3 635.9) rotate(-70)"
        />
        <rect
          id="E-61"
          data-name="E"
          className="cls-1"
          x="468.9"
          y="272.3"
          width="10"
          height="10"
          transform="translate(51.2 627.8) rotate(-70)"
        />
        <rect
          id="E-62"
          data-name="E"
          className="cls-1"
          x="478.3"
          y="275.7"
          width="10"
          height="10"
          transform="translate(54.2 638.9) rotate(-70)"
        />
        <rect
          id="E-63"
          data-name="E"
          className="cls-1"
          x="465.5"
          y="281.7"
          width="10"
          height="10"
          transform="translate(40.1 630.7) rotate(-70)"
        />
        <rect
          id="E-64"
          data-name="E"
          className="cls-1"
          x="474.9"
          y="285.1"
          width="10"
          height="10"
          transform="translate(43.1 641.8) rotate(-70)"
        />
      </g>
      <g id="F4">
        <rect
          id="F"
          className="cls-1"
          x="327.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-2"
          data-name="F"
          className="cls-1"
          x="327.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-3"
          data-name="F"
          className="cls-1"
          x="337.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-4"
          data-name="F"
          className="cls-1"
          x="337.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-5"
          data-name="F"
          className="cls-1"
          x="347.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-6"
          data-name="F"
          className="cls-1"
          x="347.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-7"
          data-name="F"
          className="cls-1"
          x="357.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-8"
          data-name="F"
          className="cls-1"
          x="357.4"
          y="287.3"
          width="10"
          height="10"
        />
      </g>
      <g id="F5">
        <rect
          id="F-9"
          data-name="F"
          className="cls-1"
          x="367.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-10"
          data-name="F"
          className="cls-1"
          x="367.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-11"
          data-name="F"
          className="cls-1"
          x="377.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-12"
          data-name="F"
          className="cls-1"
          x="377.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-13"
          data-name="F"
          className="cls-1"
          x="387.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-14"
          data-name="F"
          className="cls-1"
          x="387.4"
          y="287.3"
          width="10"
          height="10"
        />
      </g>
      <g id="F2">
        <rect
          id="F-15"
          data-name="F"
          className="cls-1"
          x="137.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-16"
          data-name="F"
          className="cls-1"
          x="137.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-17"
          data-name="F"
          className="cls-1"
          x="147.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-18"
          data-name="F"
          className="cls-1"
          x="147.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-19"
          data-name="F"
          className="cls-1"
          x="157.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-20"
          data-name="F"
          className="cls-1"
          x="157.4"
          y="287.3"
          width="10"
          height="10"
        />
      </g>
      <g id="F3">
        <rect
          id="F-21"
          data-name="F"
          className="cls-1"
          x="177.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-22"
          data-name="F"
          className="cls-1"
          x="177.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-23"
          data-name="F"
          className="cls-1"
          x="187.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-24"
          data-name="F"
          className="cls-1"
          x="187.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-25"
          data-name="F"
          className="cls-1"
          x="197.4"
          y="277.3"
          width="10"
          height="10"
        />
        <rect
          id="F-26"
          data-name="F"
          className="cls-1"
          x="197.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-27"
          data-name="F"
          className="cls-1"
          x="167.4"
          y="287.3"
          width="10"
          height="10"
        />
        <rect
          id="F-28"
          data-name="F"
          className="cls-1"
          x="167.4"
          y="277.3"
          width="10"
          height="10"
        />
      </g>
    </svg>
  );
};

export default map_day_2;
